### PR TITLE
Make ready for studio migration

### PR DESCRIPTION
**Pull request by aminlatifi**
Upgrade subgraph dependencies
Do some initialization required by a new version of subgraph packages
Renamed xdai network to gnosis

### CODE REVIEW

**Comment by aminlatifi** [comment]
Deployed to studio 
https://thegraph.com/studio/subgraph/giveth-staging---gnosis-chain/playground

**Comment by aminlatifi** [comment]
https://github.com/Giveth/giveconomy-subgraph/issues/38

**Review by mohammadranjbarz — CHANGES_REQUESTED** [review]
There is bunch of `xdai` terms in our codes, maybe it's better to change them to gnosis, WDYT?(generated files and CI/cD have xdai in them, if you search xdai in project you would see)

Screen Shot 1401-10-22 at 11 40 01


Screen Shot 1401-10-22 at 11 39 44

**Comment by aminlatifi** [comment]
> There is bunch of `xdai` terms in our codes, maybe it's better to change them to gnosis, WDYT?(generated files and CI/cD have xdai in them, if you search xdai in project you would see)
> 
> Screen Shot 1401-10-22 at 11 40 01
> 
> Screen Shot 1401-10-22 at 11 39 44

@mohammadranjbarz You are right, just pushed the update

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @aminlatifi  LGTM

**Pull request merged**
